name: "Zac"
description: "Sets up uv and prints Hello from the zac Python package"

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5

    - name: Say Hello
      shell: bash
      working-directory: ${{ github.action_path }}
      run: uv run zac
