[project]
name = "zac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mortimr", email = "github.tricolor383@passmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
zac = "zac:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pip-audit>=2.10.0",
    "ruff>=0.15.12",
    "ty>=0.0.33",
]
test = [
    "pytest>=9.0.3",
]
