aliases:
  global:
    signers: ./aliases/signers.yaml
  mainnet:
    aave: ../aliases/mainnet/aave.yaml
    tokens: ../aliases/mainnet/tokens.yaml
    safes: ./aliases/mainnet/safes.yaml
    modifiers: ./aliases/mainnet/modifiers.yaml
