aliases:
  global:
    signers: ./aliases/signers.yaml
  mainnet:
    aave: ../aliases/mainnet/aave.yaml
    compound: ../aliases/mainnet/compound.yaml
    ethena: ../aliases/mainnet/ethena.yaml
    maple: ../aliases/mainnet/maple.yaml
    tokens: ../aliases/mainnet/tokens.yaml
    metamorpho: ../aliases/mainnet/metamorpho.yaml
    morpho_blue: ../aliases/mainnet/morpho_blue.yaml
    ondo_gm: ../aliases/mainnet/ondo_gm.yaml
    ondo_ousg: ../aliases/mainnet/ondo_ousg.yaml
    lagoon: ../aliases/mainnet/lagoon.yaml
    helper: ../aliases/mainnet/helper.yaml
    safes: ./aliases/mainnet/safes.yaml
    modifiers: ./aliases/mainnet/modifiers.yaml
  sepolia:
    aave: ../aliases/sepolia/aave.yaml
    tokens: ../aliases/sepolia/tokens.yaml
    morpho_blue: ../aliases/sepolia/morpho_blue.yaml
    safes: ./aliases/sepolia/safes.yaml
    modifiers: ./aliases/sepolia/modifiers.yaml
  base:
    tokens: ../aliases/base/tokens.yaml
    morpho_blue: ../aliases/base/morpho_blue.yaml
    safes: ./aliases/base/safes.yaml
    modifiers: ./aliases/base/modifiers.yaml
