name: action-test

on: [push, pull_request]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v5

      - uses: extractions/setup-just@v4

      - run: just action-test
