name: action-test

on: [push, pull_request]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v2

      - uses: extractions/setup-just@v4

      - run: just install

      - run: just action-test
