name: contracts-test

on: [push, pull_request]

jobs:
  contracts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1

      - uses: extractions/setup-just@v4

      - run: just contracts-test
